version: "2"
services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    ### Generate admin password
    ### Run docker run --rm httpd:2.4-alpine htpasswd -nbB admin sFJVb7jF5xZfKbUm
    ### (Escape $ with $$)
    command: --admin-password '$$2y$$05$$ajJ/I01DT3mEzfNYsVWYquxWjZOihUZpd4AtH8daz2wpyUepFY8di'
    volumes:
    ### COMPOSE_CONVERT_WINDOWS_PATHS=1 (must be SET on Windows)
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    env_file:
      - variables.env 
  grafana:
    image: grafana/grafana
    restart: always
    ports:
     - "3000:3000"
    entrypoint: /etc/grafana/provisioning/entrypoint.sh
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - variables.env 
volumes:
  portainer:
  influxdb: